export type SdkClientSurface = 'integration' | 'owner' | 'widget' | 'legacy';
export type OpenApiSecurityScheme = 'ApiKeyBearer' | 'SupabaseBearer' | 'WidgetToken' | 'InternalSecret';
export type RetrySafety = 'read' | 'idempotent' | 'sideEffect';

export type SdkOperationMetadata = {
  methodName: string;
  operationId: string;
  httpMethod: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  pathTemplate: string;
  securitySchemes: readonly OpenApiSecurityScheme[];
  clientSurfaces: readonly SdkClientSurface[];
  retrySafety: RetrySafety;
};

export const INTEGRATION_CLIENT_METHODS = [
  'listGroupAdvisors',
  'getGroupAdvisor',
  'createSession',
  'getSession',
  'getSessionLedger',
  'sendOtp',
  'verifyPhone',
  'createStripeIntent',
  'createPayPalOrder',
  'authorizePayPalOrder',
  'authorizeHold',
  'startConnecting',
  'markConnected',
  'tick',
  'endAndCapture',
  'submitSessionReview',
] as const;

export const OWNER_CLIENT_METHODS = [
  'listApiKeys',
  'createApiKey',
  'rotateApiKey',
  'revokeApiKey',
  'getWidgetSecurity',
  'updateWidgetSecurity',
  'createInvite',
  'listInvites',
  'rotateInvite',
  'revokeInvite',
  'sendInvite',
  'updateGroupSlug',
  'getGroupSettings',
  'updateGroupSettings',
  'uploadGroupVoicePrompt',
  'clearGroupVoicePrompt',
  'getPayoutPolicy',
  'getOwnerPayoutPortfolio',
  'updatePayoutPolicy',
  'listOwnerAdvisors',
  'moderateAdvisor',
  'listAdvisorModerationEvents',
  'listGroupModerationEvents',
  'removeAdvisor',
  'updateGroupTheme',
  'getSetupState',
  'updateSetupState',
  'getAnalyticsOverview',
  'getAnalyticsRevenue',
  'getAnalyticsSessions',
  'getWidgetEventAnalytics',
  'listOwnerPayouts',
  'getPayoutReadiness',
  'listPayoutRuns',
  'createPayoutRun',
  'getOwnerCommissionPayoutReadiness',
  'listOwnerCommissionPayoutRuns',
  'createOwnerCommissionPayoutRun',
  'batchCreateOwnerInvites',
  'acceptInvite',
  'generateWidgetEmbedCode',
] as const;

export const WIDGET_CLIENT_METHODS = [
  'createSession',
  'getSession',
  'getSessionLedger',
  'sendOtp',
  'verifyPhone',
  'createStripeIntent',
  'createPayPalOrder',
  'authorizePayPalOrder',
  'authorizeHold',
  'startConnecting',
  'markConnected',
  'tick',
  'endAndCapture',
  'submitSessionReview',
  'mintWidgetToken',
  'getWidgetConfig',
  'listWidgetAdvisors',
  'getGroupBySlug',
  'previewInvite',
  'createWidgetCallback',
  'getWidgetCallbackStatus',
  'ingestWidgetEvent',
  'getGroupSitemap',
  'getAdvisorJsonLd',
  'getTaxonomy',
] as const;

export const LEGACY_V1_CLIENT_METHODS = [
  'listGroupAdvisors',
  'getGroupAdvisor',
  'createSession',
  'getSession',
  'getSessionLedger',
  'sendOtp',
  'verifyPhone',
  'createStripeIntent',
  'createPayPalOrder',
  'authorizePayPalOrder',
  'authorizeHold',
  'startConnecting',
  'markConnected',
  'tick',
  'endAndCapture',
  'submitSessionReview',
  'listApiKeys',
  'createApiKey',
  'rotateApiKey',
  'revokeApiKey',
  'mintWidgetToken',
  'getWidgetConfig',
  'listWidgetAdvisors',
  'getWidgetSecurity',
  'updateWidgetSecurity',
  'createInvite',
  'listInvites',
  'rotateInvite',
  'revokeInvite',
  'sendInvite',
  'getGroupBySlug',
  'updateGroupSlug',
  'getGroupSettings',
  'updateGroupSettings',
  'uploadGroupVoicePrompt',
  'clearGroupVoicePrompt',
  'getPayoutPolicy',
  'getOwnerPayoutPortfolio',
  'updatePayoutPolicy',
  'listOwnerAdvisors',
  'moderateAdvisor',
  'listAdvisorModerationEvents',
  'listGroupModerationEvents',
  'removeAdvisor',
  'updateGroupTheme',
  'getSetupState',
  'updateSetupState',
  'getAnalyticsOverview',
  'getAnalyticsRevenue',
  'getAnalyticsSessions',
  'getWidgetEventAnalytics',
  'listOwnerPayouts',
  'getPayoutReadiness',
  'listPayoutRuns',
  'createPayoutRun',
  'getOwnerCommissionPayoutReadiness',
  'listOwnerCommissionPayoutRuns',
  'createOwnerCommissionPayoutRun',
  'batchCreateOwnerInvites',
  'previewInvite',
  'acceptInvite',
  'createWidgetCallback',
  'getWidgetCallbackStatus',
  'ingestWidgetEvent',
  'getGroupSitemap',
  'getAdvisorJsonLd',
  'getTaxonomy',
  'generateWidgetEmbedCode',
] as const;

export const SDK_CLIENT_METHODS = {
  integration: INTEGRATION_CLIENT_METHODS,
  owner: OWNER_CLIENT_METHODS,
  widget: WIDGET_CLIENT_METHODS,
  legacy: LEGACY_V1_CLIENT_METHODS,
} as const;

export const SDK_OPERATION_METADATA = {
  listGroupAdvisors: { methodName: 'listGroupAdvisors', operationId: 'listIntegrationAdvisors', httpMethod: 'GET', pathTemplate: "/v1/integration/groups/{groupId}/advisors", securitySchemes: ["ApiKeyBearer", "InternalSecret"], clientSurfaces: ["legacy", "integration"], retrySafety: 'read' },
  getGroupAdvisor: { methodName: 'getGroupAdvisor', operationId: 'getIntegrationAdvisor', httpMethod: 'GET', pathTemplate: "/v1/integration/groups/{groupId}/advisors/{advisorId}", securitySchemes: ["ApiKeyBearer", "InternalSecret"], clientSurfaces: ["legacy", "integration"], retrySafety: 'read' },
  createSession: { methodName: 'createSession', operationId: 'createSession', httpMethod: 'POST', pathTemplate: "/v1/sessions", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'idempotent' },
  getSession: { methodName: 'getSession', operationId: 'getSession', httpMethod: 'GET', pathTemplate: "/v1/sessions/{sessionId}", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'read' },
  getSessionLedger: { methodName: 'getSessionLedger', operationId: 'getSessionLedger', httpMethod: 'GET', pathTemplate: "/v1/sessions/{sessionId}/ledger", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'read' },
  sendOtp: { methodName: 'sendOtp', operationId: 'sendSessionOtp', httpMethod: 'POST', pathTemplate: "/v1/sessions/{sessionId}/otp/send", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'sideEffect' },
  verifyPhone: { methodName: 'verifyPhone', operationId: 'verifySessionOtp', httpMethod: 'POST', pathTemplate: "/v1/sessions/{sessionId}/verify-phone", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'sideEffect' },
  createStripeIntent: { methodName: 'createStripeIntent', operationId: 'createSessionPaymentIntent', httpMethod: 'POST', pathTemplate: "/v1/sessions/{sessionId}/payments/create-intent", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'sideEffect' },
  createPayPalOrder: { methodName: 'createPayPalOrder', operationId: 'createSessionPayPalOrder', httpMethod: 'POST', pathTemplate: "/v1/sessions/{sessionId}/payments/paypal/create-order", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'sideEffect' },
  authorizePayPalOrder: { methodName: 'authorizePayPalOrder', operationId: 'authorizeSessionPayPalOrder', httpMethod: 'POST', pathTemplate: "/v1/sessions/{sessionId}/payments/paypal/authorize", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'sideEffect' },
  authorizeHold: { methodName: 'authorizeHold', operationId: 'authorizeSessionHold', httpMethod: 'POST', pathTemplate: "/v1/sessions/{sessionId}/authorize-hold", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'sideEffect' },
  startConnecting: { methodName: 'startConnecting', operationId: 'startSessionConnecting', httpMethod: 'POST', pathTemplate: "/v1/sessions/{sessionId}/start-connecting", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'sideEffect' },
  markConnected: { methodName: 'markConnected', operationId: 'markSessionConnected', httpMethod: 'POST', pathTemplate: "/v1/sessions/{sessionId}/mark-connected", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'sideEffect' },
  tick: { methodName: 'tick', operationId: 'tickSession', httpMethod: 'POST', pathTemplate: "/v1/sessions/{sessionId}/tick", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'sideEffect' },
  endAndCapture: { methodName: 'endAndCapture', operationId: 'endSessionAndCapture', httpMethod: 'POST', pathTemplate: "/v1/sessions/{sessionId}/end-and-capture", securitySchemes: ["ApiKeyBearer", "WidgetToken", "InternalSecret"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'sideEffect' },
  submitSessionReview: { methodName: 'submitSessionReview', operationId: 'submitSessionReview', httpMethod: 'POST', pathTemplate: "/v1/sessions/{sessionId}/reviews", securitySchemes: ["ApiKeyBearer", "WidgetToken"], clientSurfaces: ["legacy", "integration", "widget"], retrySafety: 'sideEffect' },
  listApiKeys: { methodName: 'listApiKeys', operationId: 'listOwnerApiKeys', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/api-keys", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  createApiKey: { methodName: 'createApiKey', operationId: 'createOwnerApiKey', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/api-keys", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  rotateApiKey: { methodName: 'rotateApiKey', operationId: 'rotateOwnerApiKey', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/api-keys/{keyId}/rotate", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  revokeApiKey: { methodName: 'revokeApiKey', operationId: 'revokeOwnerApiKey', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/api-keys/{keyId}/revoke", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  mintWidgetToken: { methodName: 'mintWidgetToken', operationId: 'mintWidgetToken', httpMethod: 'POST', pathTemplate: "/v1/widget/{groupId}/auth/token", securitySchemes: [], clientSurfaces: ["legacy", "widget"], retrySafety: 'sideEffect' },
  getWidgetConfig: { methodName: 'getWidgetConfig', operationId: 'getWidgetConfig', httpMethod: 'GET', pathTemplate: "/v1/widget/{groupId}/config", securitySchemes: [], clientSurfaces: ["legacy", "widget"], retrySafety: 'read' },
  listWidgetAdvisors: { methodName: 'listWidgetAdvisors', operationId: 'listWidgetAdvisors', httpMethod: 'GET', pathTemplate: "/v1/widget/{groupId}/advisors", securitySchemes: [], clientSurfaces: ["legacy", "widget"], retrySafety: 'read' },
  getWidgetSecurity: { methodName: 'getWidgetSecurity', operationId: 'getWidgetSecurity', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/widget/security", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  updateWidgetSecurity: { methodName: 'updateWidgetSecurity', operationId: 'updateWidgetSecurity', httpMethod: 'PUT', pathTemplate: "/v1/owner/groups/{groupId}/widget/security", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  createInvite: { methodName: 'createInvite', operationId: 'createOwnerInvite', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/invites", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  listInvites: { methodName: 'listInvites', operationId: 'listOwnerInvites', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/invites", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  rotateInvite: { methodName: 'rotateInvite', operationId: 'rotateOwnerInvite', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/invites/{inviteId}/rotate", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  revokeInvite: { methodName: 'revokeInvite', operationId: 'revokeOwnerInvite', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/invites/{inviteId}/revoke", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  sendInvite: { methodName: 'sendInvite', operationId: 'sendOwnerInvite', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/invites/{inviteId}/send", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  getGroupBySlug: { methodName: 'getGroupBySlug', operationId: 'getGroupBySlug', httpMethod: 'GET', pathTemplate: "/v1/groups/by-slug/{slug}", securitySchemes: [], clientSurfaces: ["legacy", "widget"], retrySafety: 'read' },
  updateGroupSlug: { methodName: 'updateGroupSlug', operationId: 'updateGroupSlug', httpMethod: 'PATCH', pathTemplate: "/v1/owner/groups/{groupId}/slug", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  getGroupSettings: { methodName: 'getGroupSettings', operationId: 'getGroupSettings', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/settings", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  updateGroupSettings: { methodName: 'updateGroupSettings', operationId: 'updateGroupSettings', httpMethod: 'PATCH', pathTemplate: "/v1/owner/groups/{groupId}/settings", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  uploadGroupVoicePrompt: { methodName: 'uploadGroupVoicePrompt', operationId: 'uploadGroupVoicePrompt', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/voice-prompts/{promptKey}", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  clearGroupVoicePrompt: { methodName: 'clearGroupVoicePrompt', operationId: 'clearGroupVoicePrompt', httpMethod: 'DELETE', pathTemplate: "/v1/owner/groups/{groupId}/voice-prompts/{promptKey}", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  getPayoutPolicy: { methodName: 'getPayoutPolicy', operationId: 'getPayoutPolicy', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/payout-policy", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  getOwnerPayoutPortfolio: { methodName: 'getOwnerPayoutPortfolio', operationId: 'getOwnerPayoutPortfolio', httpMethod: 'GET', pathTemplate: "/v1/owner/payouts/portfolio", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  updatePayoutPolicy: { methodName: 'updatePayoutPolicy', operationId: 'updatePayoutPolicy', httpMethod: 'PATCH', pathTemplate: "/v1/owner/groups/{groupId}/payout-policy", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  listOwnerAdvisors: { methodName: 'listOwnerAdvisors', operationId: 'listOwnerAdvisors', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/advisors", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  moderateAdvisor: { methodName: 'moderateAdvisor', operationId: 'moderateAdvisor', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/advisors/{advisorId}/moderate", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  listAdvisorModerationEvents: { methodName: 'listAdvisorModerationEvents', operationId: 'listAdvisorModerationEvents', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/advisors/{advisorId}/events", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  listGroupModerationEvents: { methodName: 'listGroupModerationEvents', operationId: 'listGroupModerationEvents', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/events", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  removeAdvisor: { methodName: 'removeAdvisor', operationId: 'removeAdvisor', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/advisors/{advisorId}", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  updateGroupTheme: { methodName: 'updateGroupTheme', operationId: 'updateGroupTheme', httpMethod: 'PATCH', pathTemplate: "/v1/owner/groups/{groupId}/theme", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  getSetupState: { methodName: 'getSetupState', operationId: 'getSetupState', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/setup-state", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  updateSetupState: { methodName: 'updateSetupState', operationId: 'updateSetupState', httpMethod: 'PATCH', pathTemplate: "/v1/owner/groups/{groupId}/setup-state", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  getAnalyticsOverview: { methodName: 'getAnalyticsOverview', operationId: 'getAnalyticsOverview', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/analytics/overview", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  getAnalyticsRevenue: { methodName: 'getAnalyticsRevenue', operationId: 'getAnalyticsRevenue', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/analytics/revenue", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  getAnalyticsSessions: { methodName: 'getAnalyticsSessions', operationId: 'getAnalyticsSessions', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/analytics/sessions", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  getWidgetEventAnalytics: { methodName: 'getWidgetEventAnalytics', operationId: 'getWidgetEventAnalytics', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/analytics/widget-events", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  listOwnerPayouts: { methodName: 'listOwnerPayouts', operationId: 'listOwnerPayouts', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/payouts", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  getPayoutReadiness: { methodName: 'getPayoutReadiness', operationId: 'getPayoutReadiness', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/payout-readiness", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  listPayoutRuns: { methodName: 'listPayoutRuns', operationId: 'listPayoutRuns', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/payout-runs", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  createPayoutRun: { methodName: 'createPayoutRun', operationId: 'createPayoutRun', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/payout-runs", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  getOwnerCommissionPayoutReadiness: { methodName: 'getOwnerCommissionPayoutReadiness', operationId: 'getOwnerCommissionPayoutReadiness', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/owner-commission/readiness", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  listOwnerCommissionPayoutRuns: { methodName: 'listOwnerCommissionPayoutRuns', operationId: 'listOwnerCommissionPayoutRuns', httpMethod: 'GET', pathTemplate: "/v1/owner/groups/{groupId}/owner-commission/payout-runs", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'read' },
  createOwnerCommissionPayoutRun: { methodName: 'createOwnerCommissionPayoutRun', operationId: 'createOwnerCommissionPayoutRun', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/owner-commission/payout-runs", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  batchCreateOwnerInvites: { methodName: 'batchCreateOwnerInvites', operationId: 'batchCreateOwnerInvites', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/invites/batch", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  previewInvite: { methodName: 'previewInvite', operationId: 'previewInvite', httpMethod: 'GET', pathTemplate: "/v1/invites/{token}/preview", securitySchemes: [], clientSurfaces: ["legacy", "widget"], retrySafety: 'read' },
  acceptInvite: { methodName: 'acceptInvite', operationId: 'acceptInvite', httpMethod: 'POST', pathTemplate: "/v1/invites/{token}/accept", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
  createWidgetCallback: { methodName: 'createWidgetCallback', operationId: 'createWidgetCallback', httpMethod: 'POST', pathTemplate: "/v1/widget/{groupId}/callbacks", securitySchemes: ["WidgetToken"], clientSurfaces: ["legacy", "widget"], retrySafety: 'sideEffect' },
  getWidgetCallbackStatus: { methodName: 'getWidgetCallbackStatus', operationId: 'getWidgetCallbackStatus', httpMethod: 'GET', pathTemplate: "/v1/widget/{groupId}/callbacks/status", securitySchemes: ["WidgetToken"], clientSurfaces: ["legacy", "widget"], retrySafety: 'read' },
  ingestWidgetEvent: { methodName: 'ingestWidgetEvent', operationId: 'ingestWidgetEvent', httpMethod: 'POST', pathTemplate: "/v1/widget/{groupId}/events", securitySchemes: ["WidgetToken"], clientSurfaces: ["legacy", "widget"], retrySafety: 'sideEffect' },
  getGroupSitemap: { methodName: 'getGroupSitemap', operationId: 'getGroupSitemap', httpMethod: 'GET', pathTemplate: "/v1/seo/groups/{groupSlug}/sitemap.xml", securitySchemes: [], clientSurfaces: ["legacy", "widget"], retrySafety: 'read' },
  getAdvisorJsonLd: { methodName: 'getAdvisorJsonLd', operationId: 'getAdvisorJsonLd', httpMethod: 'GET', pathTemplate: "/v1/seo/groups/{groupSlug}/advisors/{advisorId}/jsonld", securitySchemes: [], clientSurfaces: ["legacy", "widget"], retrySafety: 'read' },
  getTaxonomy: { methodName: 'getTaxonomy', operationId: 'getTaxonomy', httpMethod: 'GET', pathTemplate: "/v1/taxonomy", securitySchemes: [], clientSurfaces: ["legacy", "widget"], retrySafety: 'read' },
  generateWidgetEmbedCode: { methodName: 'generateWidgetEmbedCode', operationId: 'generateWidgetEmbedCode', httpMethod: 'POST', pathTemplate: "/v1/owner/groups/{groupId}/widget/generate", securitySchemes: ["SupabaseBearer"], clientSurfaces: ["legacy", "owner"], retrySafety: 'sideEffect' },
} as const satisfies Record<string, SdkOperationMetadata>;

export type SdkMethodName = keyof typeof SDK_OPERATION_METADATA;

export function operationMetadata(methodName: SdkMethodName): SdkOperationMetadata {
  return SDK_OPERATION_METADATA[methodName];
}
